FROM mcr.microsoft.com/azure-cli:latest

## Add image labels
LABEL maintainer="nizar.ghribi@gmail.com"
LABEL version="0.1"
LABEL description="Docker Image for Standard DEV Environment"
LABEL org.opencontainers.image.source https://github.com/nizarghribi/docker-images

# Set Environment Variables
ENV SHELL=/bin/bash \
    DOCKER_BUILDKIT=1 \
    PYTHONPATH=/usr/bin/python \
    TERRAFORM_VERSION=1.5.2

# Create a non-root user
RUN adduser -D -u 1000 vscode

# Update Alpine Software repository and install necessary packages
RUN apk --no-cache add \
    bash \
    ca-certificates \
    curl \
    git \
    python3 \
    py3-pip

# Install OhMyPosh
RUN curl -s https://ohmyposh.dev/install.sh | bash -s

# ### Install Terraform
RUN curl -fsSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o /tmp/terraform.zip && \
    unzip /tmp/terraform.zip -d /usr/bin && \
    rm /tmp/terraform.zip

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - 
ENV PATH="/root/.local/bin:${PATH}" 

# Switch to the non-root user
#USER vscode

# Entry point
CMD ["/bin/bash"]