FROM alpine:latest

## Add image labels
LABEL maintainer="nizar.ghribi@gmail.com"
LABEL version="0.1"
LABEL description="Docker Image for Standard DEV Environment"
LABEL org.opencontainers.image.source https://github.com/nizarghribi/docker-images

# Default to bash shell
ENV SHELL=/bin/bash \
    DOCKER_BUILDKIT=1

# Create a non-root user
RUN adduser -D -u 1000 vscode

# Update Alpine Software repository and install necessary packages
RUN apk --no-cache add \
    bash \
    ca-certificates \
    curl \
    git \ 
    python3

# Install OhMyPosh
RUN curl -s https://ohmyposh.dev/install.sh | bash -s

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - 
ENV PATH="/root/.local/bin:${PATH}" 

# Switch to the non-root user
#USER vscode

# Entry point
CMD ["/bin/bash"]